services:
  _defaults:
    public: true

  ##############
  # Your Module

  <module_name>.module:
    class: <module_name>
    factory: ['Module', 'getInstanceByName']
    arguments:
      - '<module_name>'

  <module_name>.context:
    class: Context
    factory: ['Context', 'getContext']

  #####################
  # PrestaShop Account

  <module_name>.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    arguments:
      - '5.0'

  <module_name>.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    arguments:
      - '@<module_name>.ps_accounts_installer'

  #####################
  # PrestaShop Billing

  <module_name>.ps_billings_context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    arguments:
    - '@<module_name>.ps_accounts_facade'
    - '@<module_name>.context'
    - true # if true, enables the sandbox mode, if false or empty, disables it

  <module_name>.ps_billings_facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
    - '@<module_name>.ps_billings_context_wrapper'
    - '@<module_name>.module'

  # Remove this if you do not need BillingService
  <module_name>.ps_billings_service:
    class: 'PrestaShopCorp\Billing\Services\BillingService'
    public: true
    arguments:
    - '@<module_name>.ps_billings_context_wrapper'
    - '@<module_name>.module'